from __future__ import annotations

import argparse
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from vision_language_localization.evaluation.report_evaluator import evaluate_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate VLM explanations from a pipeline report against expert annotations "
        "and analyze RQ3 correlations with quantitative safety metrics."
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("outputs/latest_run.json"),
        help="Pipeline report generated by scripts/run_pipeline.py",
    )
    parser.add_argument(
        "--annotations",
        type=Path,
        default=None,
        help="JSON file with expert labels per sequence (see annotations/example_annotations.json)",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("outputs"),
        help="Directory where evaluation_report.json is written",
    )
    parser.add_argument(
        "--n-perm",
        type=int,
        default=2000,
        help="Number of permutations for correlation p-values",
    )
    parser.add_argument("--seed", type=int, default=7, help="Random seed for permutation tests")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    out_file = evaluate_report(
        report_path=args.report,
        annotations_path=args.annotations,
        output_root=args.output_root,
        n_perm=args.n_perm,
        seed=args.seed,
    )

    import json

    evaluation = json.loads(out_file.read_text(encoding="utf-8"))
    summary = evaluation["summary"]

    print("=" * 72)
    print("VLM EVALUATION SUMMARY")
    print("=" * 72)
    print(f"Sequences: {summary['num_sequences']}  |  Annotated: {summary['num_annotated']}")
    print(f"Consistency (mean pairwise text similarity): {summary['consistency']['mean_text_similarity']}")
    print(f"Latency (mean per explanation, s): {summary['latency']['mean_s']}")
    print()

    metrics = summary.get("explanation_metrics") or {}
    if metrics:
        print("Explanation metrics (mean over annotated sequences):")
        for key in [
            "claim_precision",
            "claim_recall",
            "claim_f1",
            "hazard_precision",
            "hazard_recall",
            "hazard_f1",
            "hallucination_rate",
        ]:
            row = metrics.get(key)
            if row:
                print(f"  {key:<22} mean={row['mean']:<8} std={row['std']:<8} n={row['n']}")
        print()
    else:
        print("No annotated sequences found; provide --annotations for explanation metrics.\n")

    print("RQ3 correlation (VLM signals vs safety metrics, Pearson r / p):")
    shown = 0
    for row in evaluation.get("correlation_rq3", []):
        if row.get("pearson_r") is None:
            continue
        flag = " *" if row.get("pearson_p") is not None and row["pearson_p"] < 0.05 else ""
        print(
            f"  {row['vlm_signal']:<20} vs {row['safety_metric']:<18} "
            f"r={row['pearson_r']:<8} p={row['pearson_p']}{flag}"
        )
        shown += 1
    if shown == 0:
        print("  (none computed - need at least 2 sequences)")
    print()
    print(f"Evaluation report written to: {out_file}")


if __name__ == "__main__":
    main()
